package com.blog.crm.enums;

public enum ModuleName {

	LOGGER, POST, AUTHOR, SCHDULER, SMS, EMAIL, PUSHSMS, UTILITY, GENERICDAOIMPL, AUDITREPORT, SCHEDULERREPORT,
	SCHEDULER, LOCATIONMANAGEMENT, USERMANAGEMENT, SCHEDULERAUDIT, CONFIGURATIONSETTING, LOGANALYZER, WORKFLOWMANAGEMENT
}
